services:
  server:
    image: server
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    volumes:
      - build_output:/app/build
      - /tmp:/tmp
    ports:
      - "8080:8080"
    depends_on:
      - builder
    networks:
      - app-network

  builder:
    image: builder
    build:
      context: .
      dockerfile: docker/Dockerfile.builder
    volumes:
      - build_output:/app/build
    command: ["cmake", "--build", "/app/build"]

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    volumes:
      - /tmp:/tmp
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Define the named volume
volumes:
  build_output:
