# Dockerfile.server
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
# Install runtime dependencies
RUN apt update && \
    apt install -y vim lsof libc6 libssl-dev libcpprest-dev libtbb-dev python3 && \
    apt clean

# Set working directory
WORKDIR /app

# Copy the compiled binary from the builder container
COPY --from=builder /app/build/SortServer /app/


RUN chmod +x /app/SortServer

EXPOSE 8080

CMD ["./SortServer"]
