# Dockerfile.server
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
# Install runtime dependencies
RUN apt update && \
    apt install -y vim lsof libssl-dev libcpprest-dev libtbb-dev libopencv-dev python3 && \
    apt clean

# Set working directory
WORKDIR /app

# Copy the compiled binary from the builder container
COPY --from=builder /app/build/ConvNetServer /app/


COPY ../data /app/data/

RUN chmod +x /app/ConvNetServer

EXPOSE 8080

CMD ["./ConvNetServer"]
